name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_hooks: ^0.20.5
  get_it: ^8.0.3
  http: ^1.3.0
  intl: ^0.20.2
  retrofit: ^4.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway/Raleway-Regular.ttf
        - asset: assets/fonts/raleway/Raleway-Black.ttf
        - asset: assets/fonts/raleway/Raleway-Bold.ttf
        - asset: assets/fonts/raleway/Raleway-SemiBold.ttf